version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    open-pull-requests-limit: 0
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    labels:
      - "packages"
    allow:
      - dependency-type: "production"
      - dependency-type: "direct"
    commit-message:
      prefix: "pkg: "
